### ISSUE TITLE
Discuss possibility of hyphenating subjects and objects in test docstrings

### ISSUE THREAD

**Issue by bgracie** [civilcode/acme-platform#135]
Sometimes we have very long subjects or objects in our test docstrings, which can be difficult to quickly parse for comprehension.

So, I've been hyphenating parts of sentences where it seems like it'll improve readability

e.g.
`"a pool fund outflow transaction returns the reported on date"`
vs `"a pool-fund-outflow-transaction returns the reported-on-date"`

Complication:
There are some cases where it seems more readable to not hyphenate the whole object:
`"a pool-fund-inflow-transaction in cash is adjusted"`
vs. `"a pool-fund-inflow-transaction-in-cash is adjusted"`

## Guide

- Keep it simple:
  - Get something working first
  - Make notes for improvements that can be addressed after the review or in a different PR
  - Get a review
  - Then polish
- Consider large refactorings in a separate PR, e.g.:
  - renames across multiple files
  - architecture changes

## To-do List

- [ ] Break this feature down into multiple iterations
- [ ] Plan the solution for this feature
- [ ] Review the solution with the in-house product owner

## Iterations

- [ ] {iteration one}
- [ ] {iteration two}

## Peer Checklist

- [ ] review code
- [ ] check I18n (if applicable)
- [ ] review against style guides
- [ ] review database design
- [ ] review development log (SQL)
- [ ] review demo seeds
- [ ] verify feature/exploratory testing (manual)
- [ ] verify data migration
- [ ] verify acceptance test answers the 6W's (why, what, who, when, where, how)

**Comment by nicholasjhenry** [comment]
@frahugo made the observation that it appears we are highlighting types with the hyphenation
