### ISSUE TITLE
Try running our dev environment in a linux VM (locally or remotely)

### ISSUE THREAD

**Issue by bgracie** [civilcode/acme-platform#145]
## Rationale:
- stop losing bind mounts
https://github.com/civilcode/acme-platform/issues/77
- speed up compilation

## Method:
- ran gccg docker dev environment in a ubuntu/xenial virtualbox managed by Vagrant
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04
- so, macOS repo directory is mounted (in full) to virtualbox, and which is mounted with bind mounts and volumes to docker

Vagrantfile:
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
end
```

## Speed
```
time docker-compose exec application mix test
real	0m23.158s
user	0m0.336s
sys	0m0.120s
```

```
time docker-compose exec application mix compile
real	3m31.930s
user	0m0.320s
sys	0m0.120s

real	3m26.519s
user	0m0.396s
sys	0m0.084s
```

--> testing is __sometimes__ faster than on MacOS with volumes
--> compilation is faster by roughly 3m

see benchmarks from: https://github.com/civilcode/giverny-platform/pull/618

## Bind Mounts
- didn't lose bind mounts when adding/deleting/changing files on MacOS host

## Issues:
- `mix test.watch` uses `inotify` events, which are not forwarded from MacOS to VirtualBox 
https://www.virtualbox.org/ticket/10660
https://elixirforum.com/t/phoenix-livereload-in-vagrant-virtualbox/19449/6

## Guide

- Keep it simple:
  - Get something working first
  - Make notes for improvements that can be addressed after the review or in a different PR
  - Get a review
  - Then polish
- Consider large refactorings in a separate PR, e.g.:
  - renames across multiple files
  - architecture changes

## To-do List

- [ ] Break this feature down into multiple iterations
- [ ] Plan the solution for this feature
- [ ] Review the solution with the in-house product owner

## Iterations

- [ ] {iteration one}
- [ ] {iteration two}

## Peer Checklist

- [ ] review code
- [ ] check I18n (if applicable)
- [ ] review against style guides
- [ ] review database design
- [ ] review development log (SQL)
- [ ] review demo seeds
- [ ] verify feature/exploratory testing (manual)
- [ ] verify data migration
- [ ] verify acceptance test answers the 6W's (why, what, who, when, where, how)

**Comment by civilcode-pairing** [comment]
Did not improve speed or reliability enough to pursue further....also solved with Docker-Sync
