### ISSUE TITLE
Reporting on sales

### ISSUE THREAD

**Issue by frahugo** [civilcode/acme-platform#88]
## Checklist

- [ ] Obtain related documents
- [ ] Determine requirements using Event Storming or Story Mapping
- [ ] Create a data model
- [ ] Create a [Feature List](https://github.com/civilcode/playbook/blob/master/process/05%20development/fdd/feature-list.md)
- [ ] Model the state transitions
- [ ] Determine the business rules
- [ ] Create the screen wireframes

## Statement of Purpose

{what is the purpose of this module}

## To-do

{insert to-do items}

## Event Storming Model (or Story Mapping)

{insert appropriate diagram and update title}

## Data Model

{insert diagram}

## State Diagrams

{insert diagram}

## Business rules

{add business rules}

## Wireframes

{insert wireframes}
